# Shell variables
# Generated by 'wal'
wallpaper='/home/buber/Pictures/Wallpapers/sword.png'

# Special
background='#121214'
foreground='#dcd6c3'
cursor='#dcd6c3'

# Colors
color0='#121214'
color1='#C8696C'
color2='#798B7E'
color3='#918C76'
color4='#A59B74'
color5='#CAA86C'
color6='#A6A386'
color7='#dcd6c3'
color8='#9a9588'
color9='#C8696C'
color10='#798B7E'
color11='#918C76'
color12='#A59B74'
color13='#CAA86C'
color14='#A6A386'
color15='#dcd6c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
