--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/buber/Pictures/Wallpapers/sword.png"

-- Special
background="#121214"
foreground="#dcd6c3"
cursor="#dcd6c3"

-- Colors
color0="#121214"
color1="#C8696C"
color2="#798B7E"
color3="#918C76"
color4="#A59B74"
color5="#CAA86C"
color6="#A6A386"
color7="#dcd6c3"
color8="#9a9588"
color9="#C8696C"
color10="#798B7E"
color11="#918C76"
color12="#A59B74"
color13="#CAA86C"
color14="#A6A386"
color15="#dcd6c3"
